### PR TITLE
[Quarks-148] Add Apache to Quarks name in Overview

### PR DESCRIPTION
**Pull request by kathyssaunders**
Changed Quarks to be Apache Quarks in main heading and one reference.

### CODE REVIEW

**Comment by Cazen** [comment]
Hi @kathyssaunders
I think it's duplicated of #46.
Could I ask carefully why you make another PR?

**Comment by dlaboss** [comment]
Just merged #46 so it looks like this PR can be deleted.

**Comment by kathyssaunders** [comment]
My apologies--this was an error on my part.  I will delete it.

Thank you!
Kathy

**Comment by kathyssaunders** [comment]
Closing as this is a duplicate opened in error.

**Pull request closed without merging**
