### PR TITLE
[QUARKS-153] Document style guide for website consistency

### PR DESCRIPTION
**Pull request by queeniema**

### CODE REVIEW

**Comment by home4slc** [comment]
I just merged this, but I got an odd error...

Susans-MBP-318:incubator-quarks-website susancline$ sh build.sh
Configuration file: /Users/susancline/git-wip-apache-docs/incubator-quarks-website/site/_config.yml
            Source: /Users/susancline/git-wip-apache-docs/incubator-quarks-website/site
       Destination: ../content_tmp
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.828 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Switched to branch 'asf-site'
Your branch is behind 'origin/asf-site' by 9 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Committing changes to asf-site branch from master branch
[asf-site 0304cdc] from e1bd198bfd0426a24e71b588db1775039fa9fc5d
 40 files changed, 4398 insertions(+), 166 deletions(-)
 create mode 100644 content/recipes/recipe_adaptable_deadtime_filter.html
 create mode 100644 content/recipes/recipe_adaptable_polling_source.html
 create mode 100644 content/recipes/recipe_dynamic_analytic_control.html
You are now on the asf-site branch
Run git push origin asf-site to update the live site.

Susans-MBP-318:incubator-quarks-website susancline$ git push origin asf-site
To https://git-wip-us.apache.org/repos/asf/incubator-quarks-website.git
 ! [rejected]        asf-site -> asf-site (non-fast-forward)
error: failed to push some refs to 'https://git-wip-us.apache.org/repos/asf/incubator-quarks-website.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Susans-MBP-318:incubator-quarks-website susancline$ git push <-- my mistake, I did not read the error above
To https://git-wip-us.apache.org/repos/asf/incubator-quarks-website.git
 ! [rejected]        asf-site -> asf-site (non-fast-forward)
error: failed to push some refs to 'https://git-wip-us.apache.org/repos/asf/incubator-quarks-website.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Now I did a 'git pull' and I got this:

Susans-MBP-318:incubator-quarks-website susancline$ git pull
Merge made by the 'recursive' strategy.
Susans-MBP-318:incubator-quarks-website susancline$ git status
On branch asf-site
Your branch is ahead of 'origin/asf-site' by 2 commits.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

```
_site/
```

nothing added to commit but untracked files present (use "git add" to track)

Can someone help me untangle this and tell me what I should do?
Thanks, Susan

**Comment by dlaboss** [comment]
I had gotten myself into a similar situation recently.  Wasn't quite sure how I got where I did. In your case you can see that build.sh says your asf-site was behind -- presumably because someone else, like me :-), did the build.sh/push since the last time you did.

I'm getting the feeling build.sh should be ensuring your asf-site is up to date early on.  I think the following will do it:

```
$ git fetch asfclone asf-site
$ git checkout asf-site
$ git rebase asfclone/asf-site
```

I wimped out, simply blew away / recreated my asfclone, and then did the build.sh/push again.

**Comment by dlaboss** [comment]
My mistake on "asfclone" in the above git cmds.  In your clone of the asf repo, "origin" will be the repo name you need to use.

Once you successfully build/push my asf-site will be behind :-)  I'll then do the tweaks to build.sh to get my branch in the right shape and deliver that fix.

**Comment by home4slc** [comment]
Thanks @dlaboss .
I'm not sure if I was successful or not .. I did the three commands you mentioned using 'origin' instead of 'asfclone' and the last command finished like this:

M   content/urls_mydoc.txt
.git/rebase-apply/patch:18: trailing whitespace.

.git/rebase-apply/patch:26: trailing whitespace.

.git/rebase-apply/patch:34: trailing whitespace.

.git/rebase-apply/patch:42: trailing whitespace.

.git/rebase-apply/patch:50: trailing whitespace.

warning: squelched 1900 whitespace errors
warning: 1905 lines add whitespace errors.
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.

Did it work?

**Comment by dlaboss** [comment]
Uh not sure but I think so. Try the build.sh emitted git push cmd.

**Comment by dlaboss** [comment]
FYI, I just merged another PR and did a build.sh/push w/o incident.
The existing build.sh/push didn't complain, so @home4slc  I'm guessing you didn't yet do build.sh/push from #51?  (and your afs-site may be out of sync again)
Regardless, #51's content would have been part of my build/push.

**Comment by home4slc** [comment]
Thanks.. I did not because I did not have a build.sh at that point.

I’m thinking of blowing everything away and starting fresh.

Thanks,

Susan

**Pull request merged**
