### PR TITLE
Merged doc Jekyll repository with main website.

### PR DESCRIPTION
**Pull request by wmarshall484**

### CODE REVIEW

**Comment by ddebrunner** [comment]
There seems to be something strange with footer which looked to be correct wrt incubation notices, but has been moved to footer_orig and replaced with an empty footer.

**Comment by ddebrunner** [comment]
Same issue with head.

**Comment by ddebrunner** [comment]
Kathey said:

> I already merged quarks-2-pr-3 to master and deleted the branch, so the doc pull request should be against master.

https://issues.apache.org/jira/browse/QUARKS-2?focusedCommentId=15195505&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15195505

**Comment by ddebrunner** [comment]
Can you reissue the request against master?

**Comment by wmarshall484** [comment]
There was a name collision for:
_includes/head.html
_includes/footer.html
_layouts/default.html

I renamed the files from the main landing page to *_orig.html, and updated any corresponding files. The "blank" footers are for the documentation pages.

**Comment by wmarshall484** [comment]
Recreated to merge into master.

**Comment by ddebrunner** [comment]
> I renamed the files from the main landing page to *_orig.html

Somewhat confusing, maybe the files could be given logical names. _orig tends to be used for when a file has been replaced with a newer version. I would have expected something like footer & footer_doc or footer_main and footer_doc.

**Pull request closed without merging**
