### PR TITLE
Make video dynamically sized.

### PR DESCRIPTION
**Pull request by Alex-Cook4**
Video was overlapping with text in certain formats.

### CODE REVIEW

**Comment by Cazen** [comment]
LGTM
And It's just my opinion but how about give some frameborder(maybe 3)?

**Comment by Alex-Cook4** [comment]
@Cazen good idea on the frameborder! I'm not familiar with frameborder, but as a html property, it only takes 0|1. I changed it to 1. That gives us: 

image

What were you thinking with the 3? 

I'm also not very happy with how I did the dynamic sizing since I had to give the outside dive a defined height:290px in order for the percentages to work. Maybe you're more familiar with iframes and know a better way? 

```
<div style="height:290px;" class="col-lg-7 col-sm-pull-5 col-sm-6">  
          <iframe style="width:85%;height:100%" src="//www.youtube.com/embed/Xqns7yVNDnk" frameborder="1" allowfullscreen></iframe>
</div>
```

**Comment by Cazen** [comment]
Good day @Alex-Cook4 
- Sorry for confusing. I thought there is not frameborder setting in your change because video's bottom line is not presented. But it's not(And 0 or 1 is right. 3 is mistake). It seems slightly truncated. Now I think frameborder is no correlation in this problem(unnecessary). Sorry again.
- I think this issue related on responsive video issue. In fact, I think there is no problem with youtube size is automatically adjusted depending on the size of the window and accurately played with no error. So how about this way like below?

```
<div class="col-lg-6 col-sm-pull-5 col-sm-6">
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//www.youtube.com/embed/Xqns7yVNDnk" allowfullscreen></iframe>
    </div>
</div>
```
- Of course, I'm not an expert on bootstrap. Please tell me if I was wrong or there is better way to solve this problem. I'm happy to hear that. :)

**Comment by Alex-Cook4** [comment]
@Cazen that's exactly what I was looking for. Thank you! 

With my latest commit, this should be ready to merge.

**Comment by Alex-Cook4** [comment]
This is ready for merge.

**Comment by Cazen** [comment]
Hi @Alex-Cook4 
I'm very sorry and didn't mean to bother you. I know you point out exactly about resizing issue and PR was great.
But Could I kindly ask that did you intend to expand youtube screen?(Size after this patch is larger than previous fixed screen size)
And other events are going to be opened soon, so I hope apply this patch in the early hours
(Could Any committers please review this patch? I do not have commit privilege yet)

**Pull request merged**
