### PR TITLE
[QUARKS-127] String -> String image doesn't match text

### PR DESCRIPTION
**Pull request by Cazen**
The amazing dare JPG diff available!

### CODE REVIEW

**Comment by home4slc** [comment]
When I go to the apache website here: http://quarks.incubator.apache.org/docs/common-quarks-operations.html

The image appears correct.  It shows an incoming java.lang.String then a Stream.map() box then an outgoing java.lang.Integer.

Could this change have already been made?
tstream_map

**Comment by Cazen** [comment]
Good day @home4slc 
I thought this image related in last one(performing stateful operations)
Please tell me if I was wrong
Thank you :)

**Comment by home4slc** [comment]
Good day to you @Cazen - you are correct!  I apologize for the error.  Thanks for your contribution.

**Comment by Cazen** [comment]
Thank you for review :) Have a good day!

**Pull request merged**
